use std::path::{Path, PathBuf};

use spec_parser::schema::Target;
use tracing::info;

use crate::error::ForgeError;
use crate::tools::ToolRunner;

/// State for a prepared ext4 QCOW2 disk image, ready for Phase 1 population.
#[derive(Debug)]
pub struct PreparedExt4 {
    pub raw_path: PathBuf,
    pub qcow2_path: PathBuf,
    pub device: String,
    pub efi_part: String,
    pub root_part: String,
    pub mount_dir: tempfile::TempDir,
}

impl PreparedExt4 {
    /// The path where the root partition is mounted; Phase 1 populates into this.
    pub fn root_mount(&self) -> &Path {
        self.mount_dir.path()
    }
}

/// Phase 2 prepare: create raw disk, partition, format, and mount the root partition.
///
/// Returns a `PreparedExt4` whose `root_mount()` is the mounted ext4 root —
/// Phase 1 should populate the rootfs directly into that directory.
pub async fn prepare_ext4(
    target: &Target,
    output_dir: &Path,
    runner: &dyn ToolRunner,
) -> Result<PreparedExt4, ForgeError> {
    let disk_size = target
        .disk_size
        .as_deref()
        .ok_or(ForgeError::MissingDiskSize)?;

    let raw_path = output_dir.join(format!("{}.raw", target.name));
    let qcow2_path = output_dir.join(format!("{}.qcow2", target.name));
    let raw_str = raw_path.to_str().unwrap();

    info!(disk_size, "Step 1: Creating raw disk image");
    crate::tools::qemu_img::create_raw(runner, raw_str, disk_size).await?;

    info!("Step 2: Attaching loopback device");
    let device = crate::tools::loopback::attach(runner, raw_str).await?;
    let _ = crate::tools::loopback::partprobe(runner, &device).await;

    info!(device = %device, "Step 3: Creating GPT partition table");
    let (efi_part, root_part) =
        crate::tools::partition::create_gpt_efi_root(runner, &device).await?;

    crate::tools::loopback::partprobe(runner, &device).await?;

    info!("Step 4: Formatting partitions");
    crate::tools::partition::mkfs_fat32(runner, &efi_part).await?;
    crate::tools::partition::mkfs_ext4(runner, &root_part).await?;

    let mount_dir = tempfile::tempdir().map_err(ForgeError::StagingSetup)?;
    let mount_str = mount_dir.path().to_str().unwrap();

    info!("Step 5: Mounting root partition at {}", mount_str);
    crate::tools::partition::mount(runner, &root_part, mount_str).await?;

    Ok(PreparedExt4 {
        raw_path,
        qcow2_path,
        device,
        efi_part,
        root_part,
        mount_dir,
    })
}

/// Phase 2 finalize: mount EFI, bind-mount pseudofs, install GRUB, unmount everything.
pub async fn finalize_ext4(
    prepared: &PreparedExt4,
    runner: &dyn ToolRunner,
) -> Result<(), ForgeError> {
    let mount_str = prepared.mount_dir.path().to_str().unwrap();

    info!("Finalize step 1: Mounting EFI partition");
    let efi_mount = prepared.mount_dir.path().join("boot/efi");
    std::fs::create_dir_all(&efi_mount)?;
    let efi_mount_str = efi_mount.to_str().unwrap();
    crate::tools::partition::mount(runner, &prepared.efi_part, efi_mount_str).await?;

    info!("Finalize step 2: Writing /etc/fstab with partition UUIDs");
    // Get filesystem UUIDs so GRUB and the kernel use UUIDs instead of device names
    // (the loopback device names like /dev/loop0p2 are only valid during build)
    let root_uuid = get_blkid_uuid(runner, &prepared.root_part).await?;
    let efi_uuid = get_blkid_uuid(runner, &prepared.efi_part).await?;

    let fstab = format!(
        "# /etc/fstab - generated by forger\n\
         UUID={root_uuid}\t/\text4\terrors=remount-ro\t0\t1\n\
         UUID={efi_uuid}\t/boot/efi\tvfat\tumask=0077\t0\t1\n"
    );
    let fstab_path = prepared.mount_dir.path().join("etc/fstab");
    std::fs::write(&fstab_path, &fstab).map_err(|e| ForgeError::Qcow2Build {
        step: "write /etc/fstab".to_string(),
        detail: e.to_string(),
    })?;

    info!("Finalize step 3: Bind-mounting /dev, /proc, /sys");
    let dev_mount = format!("{mount_str}/dev");
    let proc_mount = format!("{mount_str}/proc");
    let sys_mount = format!("{mount_str}/sys");
    std::fs::create_dir_all(&dev_mount)?;
    std::fs::create_dir_all(&proc_mount)?;
    std::fs::create_dir_all(&sys_mount)?;
    crate::tools::partition::bind_mount(runner, "/dev", &dev_mount).await?;
    crate::tools::partition::bind_mount(runner, "/proc", &proc_mount).await?;
    crate::tools::partition::bind_mount(runner, "/sys", &sys_mount).await?;

    info!("Finalize step 4: Installing GRUB bootloader");
    runner
        .run(
            "chroot",
            &[
                mount_str,
                "/usr/sbin/grub-install",
                "--target=x86_64-efi",
                "--efi-directory=/boot/efi",
                "--no-nvram",
            ],
        )
        .await?;

    // Regenerate initramfs to pick up any modules added by overlays (e.g., virtio drivers).
    // Only relevant for Linux images that have update-initramfs.
    // Check inside the chroot's PATH-accessible location.
    let has_initramfs = prepared.mount_dir.path().join("usr/sbin/update-initramfs").exists()
        || prepared.mount_dir.path().join("usr/bin/update-initramfs").exists();
    if has_initramfs {
        info!("Finalize step 5: Regenerating initramfs");
        runner
            .run("chroot", &[mount_str, "update-initramfs", "-u"])
            .await?;
    } else {
        info!("Finalize step 5: Skipped (no update-initramfs found)");
    }

    info!("Finalize step 6: Generating GRUB config");
    runner
        .run(
            "chroot",
            &[mount_str, "/usr/sbin/grub-mkconfig", "-o", "/boot/grub/grub.cfg"],
        )
        .await?;

    // Fix root device references: grub-mkconfig bakes in the loopback device name
    // (e.g., /dev/loop0p2) because it probes the live mount table. Replace with UUID.
    info!("Finalize step 7: Fixing GRUB root device to use UUID");
    let grub_cfg_path = prepared.mount_dir.path().join("boot/grub/grub.cfg");
    if grub_cfg_path.exists() {
        let grub_cfg = std::fs::read_to_string(&grub_cfg_path).map_err(|e| {
            ForgeError::Qcow2Build {
                step: "read grub.cfg".to_string(),
                detail: e.to_string(),
            }
        })?;

        // Replace root=/dev/loopXpY with root=UUID=<uuid>
        let fixed = grub_cfg
            .replace(
                &format!("root={}", prepared.root_part),
                &format!("root=UUID={root_uuid}"),
            )
            .replace(
                &format!("root={}", prepared.device),
                &format!("root=UUID={root_uuid}"),
            );

        std::fs::write(&grub_cfg_path, &fixed).map_err(|e| ForgeError::Qcow2Build {
            step: "write fixed grub.cfg".to_string(),
            detail: e.to_string(),
        })?;
    }

    info!("Finalize step 8: Unmounting");
    crate::tools::partition::umount(runner, &sys_mount).await?;
    crate::tools::partition::umount(runner, &proc_mount).await?;
    crate::tools::partition::umount(runner, &dev_mount).await?;
    crate::tools::partition::umount(runner, efi_mount_str).await?;
    crate::tools::partition::umount(runner, mount_str).await?;

    Ok(())
}

/// Retrieve the filesystem UUID from a block device using `blkid`.
async fn get_blkid_uuid(runner: &dyn ToolRunner, device: &str) -> Result<String, ForgeError> {
    let output = runner
        .run("blkid", &["-s", "UUID", "-o", "value", device])
        .await?;
    let uuid = output.stdout.trim().to_string();
    if uuid.is_empty() {
        return Err(ForgeError::Qcow2Build {
            step: format!("get UUID for {device}"),
            detail: "blkid returned empty UUID".to_string(),
        });
    }
    Ok(uuid)
}

/// Cleanup: detach loopback, convert raw→qcow2 (if `convert` is true), remove raw file.
///
/// Always runs, even if earlier phases failed — the loopback device must be detached.
pub async fn cleanup_ext4(
    prepared: PreparedExt4,
    convert: bool,
    runner: &dyn ToolRunner,
) -> Result<(), ForgeError> {
    info!("Cleanup: detaching loopback device");
    let detach_result = crate::tools::loopback::detach(runner, &prepared.device).await;

    if convert {
        let raw_str = prepared.raw_path.to_str().unwrap();
        let qcow2_str = prepared.qcow2_path.to_str().unwrap();

        info!("Cleanup: converting raw -> qcow2");
        crate::tools::qemu_img::convert_to_qcow2(runner, raw_str, qcow2_str).await?;
    }

    // Clean up raw file
    std::fs::remove_file(&prepared.raw_path).ok();

    detach_result?;

    if convert {
        info!(path = %prepared.qcow2_path.display(), "QCOW2 (ext4) image created");
    }

    Ok(())
}
