[Unit]
Description=Serial Getty on ttyS0
After=systemd-user-sessions.service plymouth-quit-wait.service getty-pre.target
Before=getty.target

[Service]
ExecStart=-/sbin/agetty -o '-p -- \\u' --keep-baud 115200,57600,38400,9600 ttyS0 $TERM
Type=idle
Restart=always
RestartSec=0
UtmpIdentifier=ttyS0
TTYPath=/dev/ttyS0
TTYReset=yes
TTYVHangup=yes
KillMode=process

[Install]
WantedBy=getty.target
